name: CI for building Camp

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - macos-15-intel
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.x
      - name: Setup Cygwin
        if: matrix.os == 'windows-latest'
        uses: cygwin/cygwin-install-action@v6
        with:
          packages:
            make
            zip
      - name: Configure Camp
        run: make vars
      - name: Build Camp
        run: make zip
